### ISSUE TITLE
Request: Remove TextWithSlug

### ISSUE THREAD

**Issue by dillingham** [benjaminhirsch/nova-slug-field#2]
Would it be possible to just use `Slug` and not `TextWithSlug`

```php
ID::make()->sortable(),
Unique::make('Email'),
Slug::make('Slug')->from('Email'),
```

**Comment by benjaminhirsch** [comment]
Hey @dillingham,  thank you for your suggestion. I will have a look into it and test if it's possible without running into problems. :)

**Comment by benjaminhirsch** [comment]
Sorry for beeing that  quiet at the moment regarding this issue, but it's still on my list and I hopefully will find a good solution for it any time soon. :)

**Comment by niladam** [comment]
This would be a great addition and it would make more sense. It'll stop polluting your fields array..

**Comment by ArmeniaH** [comment]
Hey guys, very useful field type, unfortunately I can't use it because my case is similar to this one.

It will be much more effective, if we could specify a slug field, and specify from which field it should be slugified.

I have Place field, and I want to create a slug from address, so I would do something like

```Place::make('address') ...```
```Slug::make('slug')->from('address')```

**Comment by dillingham** [comment]
Hey @benjaminhirsch :) any chance of this? or should I close?

**Comment by benjaminhirsch** [comment]
Hey @dillingham, please don't, I still like the idea but still hadn't enough time since my last comment to get my head into it. I'm currently in the process of planning 🤔  something new which relates to Laravel and Nova which also involves the slug generation. This would then result in a major revamp of the current implementaion of my  slug field package which could then potentially include your proposal. 😄

**Comment by dillingham** [comment]
@benjaminhirsch how exciting! If there is any way to contribute or provide feedback I’m happy to help if I can.

**Comment by niladam** [comment]
I'd like to give a hand as well! Get a plan up and I'll be glad to help out.

**Comment by dillingham** [comment]
You can make it one field by setting a watcher on Slug's component 

`Slug::make('Slug')->from('some-field-attribute')`

```php
    public function from($attribute)
    {
        $this->withMeta(['slug_field_attribute' => $attribute]);

        return $this;
    }
```

```js
this.$parent.$children.forEach(component => {
    if(component.field !== undefined && component.field.attribute == this.field.slug_field_attribute) {
	    let attribute = 'value'
	    if(component.field.component === 'belongs-to-field') {
	        attribute = 'selectedResource';
	    }
	    component.$watch(attribute, (value) => {
	        this.slugValue = (value && attribute == 'selectedResource') ? value.value : value;
	    }, { immediate: true });
   }
})
```
I used a similar method in my https://github.com/dillingham/nova-ajax-select package and it worked nicely
